<?php

namespace  YiluTech\YiMQ\Tests\Feature;

use YiluTech\YiMQ\ClientManager;
use YiluTech\YiMQ\Constants\MessageAction;
use YiluTech\YiMQ\Laravel\LaravelClient;
use YiluTech\YiMQ\Messages\TransMessage;
use YiluTech\YiMQ\Tests\TestCase;

class RealTest extends TestCase
{
    protected LaravelClient $client;
    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        /* @var $clientManager ClientManager */
        $clientManager = resolve(ClientManager::class);
        $client = $clientManager->client();
        $this->client = $client->getLaravelClient();

        $client->testClear();
    }

    public function test_example()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }

    function testPdoEc(){

        for ($i=0;$i<1;$i++){
            dump($i);
            $result = $this->client->transaction("test",function (TransMessage $trans){
                $trans->ec("user@UserCreate")->join();
//                $trans->ec("user@UserTransCreate")->join();
                return "success";
            })->begin();
//            usleep(1000*30);
        }


        $this->assertDatabaseHas($this->client->messageTable(),['action'=>MessageAction::SUBMITTING]);
    }

}
