<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

namespace YiluTech\YiMQ\Grpc\Server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>server.PrepareRequest</code>
 */
class PrepareRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string type = 2;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string relation_id = 3;</code>
     */
    protected $relation_id = '';
    /**
     * Generated from protobuf field <code>string consumer = 4;</code>
     */
    protected $consumer = '';
    /**
     * Generated from protobuf field <code>string processor = 5;</code>
     */
    protected $processor = '';
    /**
     * Generated from protobuf field <code>bytes data = 6;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $type
     *     @type string $relation_id
     *     @type string $consumer
     *     @type string $processor
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \YiluTech\YiMQ\Grpc\GPBMetadata\Server::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string relation_id = 3;</code>
     * @return string
     */
    public function getRelationId()
    {
        return $this->relation_id;
    }

    /**
     * Generated from protobuf field <code>string relation_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRelationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->relation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string consumer = 4;</code>
     * @return string
     */
    public function getConsumer()
    {
        return $this->consumer;
    }

    /**
     * Generated from protobuf field <code>string consumer = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumer($var)
    {
        GPBUtil::checkString($var, True);
        $this->consumer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string processor = 5;</code>
     * @return string
     */
    public function getProcessor()
    {
        return $this->processor;
    }

    /**
     * Generated from protobuf field <code>string processor = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProcessor($var)
    {
        GPBUtil::checkString($var, True);
        $this->processor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 6;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

