<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

namespace YiluTech\YiMQ\Grpc\Server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>server.TransChildPrepareRequest</code>
 */
class TransChildPrepareRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message_id = 1;</code>
     */
    protected $message_id = '';
    /**
     * Generated from protobuf field <code>.server.ChildMessage child = 2;</code>
     */
    protected $child = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message_id
     *     @type \YiluTech\YiMQ\Grpc\Server\ChildMessage $child
     * }
     */
    public function __construct($data = NULL) {
        \YiluTech\YiMQ\Grpc\GPBMetadata\Server::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message_id = 1;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->message_id;
    }

    /**
     * Generated from protobuf field <code>string message_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.server.ChildMessage child = 2;</code>
     * @return \YiluTech\YiMQ\Grpc\Server\ChildMessage|null
     */
    public function getChild()
    {
        return $this->child;
    }

    public function hasChild()
    {
        return isset($this->child);
    }

    public function clearChild()
    {
        unset($this->child);
    }

    /**
     * Generated from protobuf field <code>.server.ChildMessage child = 2;</code>
     * @param \YiluTech\YiMQ\Grpc\Server\ChildMessage $var
     * @return $this
     */
    public function setChild($var)
    {
        GPBUtil::checkMessage($var, \YiluTech\YiMQ\Grpc\Server\ChildMessage::class);
        $this->child = $var;

        return $this;
    }

}

